<a href="https://colab.research.google.com/github/Joaogalescky/Ciencia-de-Dados---2024/blob/main/Pandas_exercicio_enem_aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercício

In [ ]:
#Importação da biblioteca Pandas
import pandas as pd

## Base dados

**Fonte da base de dados**

Enem 1998  
[Microdados do Exame Nacional do Ensino Médio - Enem](http://www.dados.gov.br/dataset/microdados-do-exame-nacional-do-ensino-medio-enem)  

**Documentação da base de dados**  

Para entender a base, acesse a descrição dos campos, disponível neste [link](https://docs.google.com/spreadsheets/d/1tKI5o9wBzBh_SaRccHJKwEzqIekqhyze/edit#gid=1105751035).

**Carregamento da base**  

Para carregar a base em um DataFrame Pandas, execute:
Para acessar o arquivo com a base é necessário solicitar acesso ao Google Drive. No caso desta aula, a base de dados está compartilhada entre todos os alunos incluídos na turma do Google Classroom.

**Google Colaboratory**  

Para execuções utilizando o ambiente do Google Colab, execute o código abaixo. A primeira vez que for executado, será solicitado um código de acesso. Para obter esse código, basta clicar no link gerado e seguir as instruções.
```python
#Solicita acesso ao Google Drive
from google.colab import drive
drive.mount('/drive')

#Carrega a base de dados direto do Google Drive (Executando no Google Colab)
enem98 = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/ENEM/1998/MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )
```
**Jupyter**  

Para execuções no Jupyter:
```python
#Colocar a base no mesmo diretório em que está executando o arquivo jupyter
#enem98 = pd.read_csv('./MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )

```

In [ ]:
# Solicita acesso ao Google Drive
from google.colab import drive
drive.mount('/drive')

# Carrega a base de dados direto do Google Drive (Executando no Google Colab)
enem98 = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/ENEM/1998/MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )

Mounted at /drive

**Exercícios**

Sobre a base de dados referente ao ENEM do ano de 1998, responda as questões abaixo utilizando a biblioteca Pandas.

Sobre a base:
1. Quantas linhas existem na base?
1. Quantas colunas existem?

In [ ]:
print(f'N. Linhas: {len(enem98)}')
print(f'N. Colunas: {len(enem98.columns)}')

N. Linhas: 157221
N. Colunas: 163

Obtenha cada informação solicitada a seguir:
- Quantos alunos foram matriculados?

In [ ]:
len(enem98)

157221

- Quantos alunos matricularam-se no ENEM por estado?

In [ ]:
enem98['SG_UF_RESIDENCIA'].value_counts()

PR    53722
RJ    36908
MG    23412
PE    10295
SP     8845
RN     4492
ES     3013
MT     1726
SC     1313
MS     1159
RS      997
RR      967
CE      667
AC      570
GO      479
AM      456
SE      344
PB      303
PA      288
DF      243
BA      180
AL      166
RO      111
PI      103
MA       90
TO       48
AP       47
Name: SG_UF_RESIDENCIA, dtype: int64

- Quantos estudantes matriculados não realizaram a prova?

In [ ]:
enem98['TP_PRESENCA'].dtypes

dtype('int64')

In [ ]:
len(enem98[enem98['TP_PRESENCA'] == 0])

41646

- Dos estudantes matriculados, quantos não realizaram a prova, por estado?

In [ ]:
faltantes = enem98[enem98['TP_PRESENCA'] == 0]
faltantes['SG_UF_RESIDENCIA'].value_counts()

RJ    14612
MG     8733
PR     6072
PE     4630
RN     1908
SP     1412
MT      534
RR      421
ES      363
SC      312
AC      202
RS      197
AM      101
MS       89
SE       55
CE       45
DF       44
PA       40
GO       36
PI       35
PB       34
AL       14
RO       12
BA       10
MA       10
TO        4
AP        1
Name: SG_UF_RESIDENCIA, dtype: int64

- Qual é idade do(a) estudante mais velho(a)?

In [ ]:
enem98['NU_IDADE'].max()

67.0

- Quantos estudantes empatam com a idade mais velha?

In [ ]:
print(len(enem98[enem98['NU_IDADE'] == maxIdade]))
enem98[enem98['NU_IDADE'] == maxIdade]

3

,NU_INSCRICAO,NU_ANO,NU_IDADE,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_PRESENCA,CO_PROVA,...,Q128,Q129,Q130,Q131,Q132,Q133,Q134,Q135,Q136,Q137
66629,66630,1998,67.0,M,3303500.0,NOVA IGUACU,33.0,RJ,1,A,...,.,.,.,.,.,.,.,.,.,.
84874,84875,1998,67.0,F,3526704.0,LEME,35.0,SP,1,A,...,B,D,A,A,B,B,A,A,A,A
126892,126893,1998,67.0,F,4104402.0,CANDIDO DE ABREU,41.0,PR,1,B,...,B,B,B,A,B,C,C,B,A,C

- Os estudantes com a idade mais mais velha são de quais estados?

In [ ]:
enem98[enem98['NU_IDADE'] == maxIdade]['SG_UF_RESIDENCIA'].unique()

array(['RJ', 'SP', 'PR'], dtype=object)

Qual é a idade do(a) estudante mais novo(a) do Paraná?

In [ ]:
idadeMinPR = enem98[enem98['SG_UF_RESIDENCIA'] == 'PR']['NU_IDADE'].min()
print(idadeMinPR)

10.0

- Quantos estudantes possuem a mesma idade do estudante mais novo no Paraná?

In [ ]:
len(enem98[enem98['NU_IDADE'] == idadeMinPR])

13

- De quais cidades são os estudantes com a menor idade?

In [ ]:
enem98PR = enem98[enem98['SG_UF_RESIDENCIA'] == 'PR']
enem98PR[enem98PR['NU_IDADE'] == idadeMinPR]

,NU_INSCRICAO,NU_ANO,NU_IDADE,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_PRESENCA,CO_PROVA,...,Q128,Q129,Q130,Q131,Q132,Q133,Q134,Q135,Q136,Q137
120076,120077,1998,10.0,F,4125902.0,SAO PEDRO DO PARANA,41.0,PR,1,B,...,A,B,A,A,B,C,C,C,A,C
135626,135627,1998,10.0,F,4118501.0,PATO BRANCO,41.0,PR,1,Z,...,A,A,A,B,B,C,C,B,*,C
141718,141719,1998,10.0,M,4101200.0,ANTONINA,41.0,PR,1,B,...,A,B,A,A,B,C,B,B,A,C
148326,148327,1998,10.0,M,4125001.0,SAO JOAO DO IVAI,41.0,PR,1,Z,...,B,A,A,A,A,A,A,A,B,A

In [ ]:
enem98PR[enem98PR['NO_MUNICIPIO_RESIDENCIA'] == 'LUIZIANA']

,NU_INSCRICAO,NU_ANO,NU_IDADE,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_PRESENCA,CO_PROVA,...,Q128,Q129,Q130,Q131,Q132,Q133,Q134,Q135,Q136,Q137
95237,95238,1998,24.0,F,4113734.0,LUIZIANA,41.0,PR,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95249,95250,1998,17.0,M,4113734.0,LUIZIANA,41.0,PR,1,G,...,B,B,A,A,C,C,B,C,A,C
95260,95261,1998,32.0,M,4113734.0,LUIZIANA,41.0,PR,1,A,...,A,A,A,B,B,C,C,C,A,C
95263,95264,1998,26.0,F,4113734.0,LUIZIANA,41.0,PR,1,Z,...,B,B,A,B,B,C,B,B,A,A
95264,95265,1998,17.0,M,4113734.0,LUIZIANA,41.0,PR,1,Z,...,*,C,A,C,B,C,B,B,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107022,107023,1998,19.0,M,4113734.0,LUIZIANA,41.0,PR,1,B,...,B,D,D,A,B,C,C,B,A,B
107025,107026,1998,17.0,F,4113734.0,LUIZIANA,41.0,PR,1,G,...,B,B,A,A,C,C,C,A,A,C
107033,107034,1998,17.0,M,4113734.0,LUIZIANA,41.0,PR,1,B,...,B,B,C,A,A,B,A,A,B,A
107035,107036,1998,23.0,M,4113734.0,LUIZIANA,41.0,PR,1,A,...,B,B,A,A,A,C,A,B,*,B
107130,107131,1998,NaN,M,4113734.0,LUIZIANA,41.0,PR,1,B,...,B,C,A,B,B,B,B,A,B,A

- No Paraná, qual a porcentagem de estudantes por sexo?

In [ ]:
enem98PR_Sexo = enem98PR['TP_SEXO'].value_counts()/len(enem98PR)*100
enem98PR_Sexo

F    59.904695
M    40.095305
Name: TP_SEXO, dtype: float64